(function () {
    const SUBJECT_ID = "kokyo";
    const SUBJECT_NAME = "公共";
    const SUBJECT_ORDER = 3;

    const questions = [
        { "q": "この国はどこ？", "a": "アイスランド", "img": "images/kokyo/アイスランド.png" },
        { "q": "この国はどこ？", "a": "イギリス", "img": "images/kokyo/イギリス.png" },
        { "q": "この国はどこ？", "a": "イタリア", "img": "images/kokyo/イタリア.png" },
        { "q": "この国はどこ？", "a": "ウクライナ", "img": "images/kokyo/ウクライナ.png" },
        { "q": "この国はどこ？", "a": "オーストリア", "img": "images/kokyo/オーストリア.png" },
        { "q": "この国はどこ？", "a": "オランダ", "img": "images/kokyo/オランダ.png" },
        { "q": "この国はどこ？", "a": "ギリシャ", "img": "images/kokyo/ギリシャ.png" },
        { "q": "この国はどこ？", "a": "スイス", "img": "images/kokyo/スイス.png" },
        { "q": "この国はどこ？", "a": "スウェーデン", "img": "images/kokyo/スウェーデン.png" },
        { "q": "この国はどこ？", "a": "スペイン", "img": "images/kokyo/スペイン.png" },
        { "q": "この国はどこ？", "a": "デンマーク", "img": "images/kokyo/デンマーク.png" },
        { "q": "この国はどこ？", "a": "ドイツ", "img": "images/kokyo/ドイツ.png" },
        { "q": "この国はどこ？", "a": "ノルウェー", "img": "images/kokyo/ノルウェー.png" },
        { "q": "この国はどこ？", "a": "ハンガリー", "img": "images/kokyo/ハンガリー.png" },
        { "q": "この国はどこ？", "a": "フィンランド", "img": "images/kokyo/フィンランド.png" },
        { "q": "この国はどこ？", "a": "フランス", "img": "images/kokyo/フランス.png" },
        { "q": "この国はどこ？", "a": "ブルガリア", "img": "images/kokyo/ブルガリア.png" },
        { "q": "この国はどこ？", "a": "ベルギー", "img": "images/kokyo/ベルギー.png" },
        { "q": "この国はどこ？", "a": "ポーランド", "img": "images/kokyo/ポーランド.png" },
        { "q": "この国はどこ？", "a": "ポルトガル", "img": "images/kokyo/ポルトガル.png" },
        { "q": "この国はどこ？", "a": "ロシア", "img": "images/kokyo/ロシア.png" },
        { "q": "この国はどこ？", "a": "モンゴル", "img": "images/kokyo/モンゴル.png" },
        { "q": "この国はどこ？", "a": "カザフスタン", "img": "images/kokyo/カザフスタン.png" },
        { "q": "この国はどこ？", "a": "中国", "img": "images/kokyo/中国.png" },
        { "q": "この国はどこ？", "a": "韓国", "img": "images/kokyo/韓国.png" },
        { "q": "この国はどこ？", "a": "ベトナム", "img": "images/kokyo/ベトナム.png" },
        { "q": "この国はどこ？", "a": "タイ", "img": "images/kokyo/タイ.png" },
        { "q": "この国はどこ？", "a": "ミャンマー", "img": "images/kokyo/ミャンマー.png" },
        { "q": "この国はどこ？", "a": "バングラデシュ", "img": "images/kokyo/バングラデシュ.png" },
        { "q": "この国はどこ？", "a": "フィリピン", "img": "images/kokyo/フィリピン.png" },
        { "q": "この国はどこ？", "a": "インドネシア", "img": "images/kokyo/インドネシア.png" },
        { "q": "この国はどこ？", "a": "東ティモール", "img": "images/kokyo/東ティモール.png" },
        { "q": "この国はどこ？", "a": "マレーシア", "img": "images/kokyo/マレーシア.png" },
        { "q": "この国はどこ？", "a": "インド", "img": "images/kokyo/インド.png" },
        { "q": "この国はどこ？", "a": "パキスタン", "img": "images/kokyo/パキスタン.png" },
        { "q": "この国はどこ？", "a": "アフガニスタン", "img": "images/kokyo/アフガニスタン.png" },
        { "q": "この国はどこ？", "a": "シリア", "img": "images/kokyo/シリア.png" },
        { "q": "この国はどこ？", "a": "イラン", "img": "images/kokyo/イラン.png" },
        { "q": "この国はどこ？", "a": "サウジアラビア", "img": "images/kokyo/サウジアラビア.png" },
        { "q": "この国はどこ？", "a": "アラブ首長国連邦", "img": "images/kokyo/アラブ首長国連邦.png" },
        { "q": "この国はどこ？", "a": "カナダ", "img": "images/kokyo/カナダ.png" },
        { "q": "この国はどこ？", "a": "アメリカ", "img": "images/kokyo/アメリカ.png" },
        { "q": "この国はどこ？", "a": "メキシコ", "img": "images/kokyo/メキシコ.png" },
        { "q": "この国はどこ？", "a": "バハマ", "img": "images/kokyo/バハマ.png" },
        { "q": "この国はどこ？", "a": "キューバ", "img": "images/kokyo/キューバ.png" },
        { "q": "この国はどこ？", "a": "ジャマイカ", "img": "images/kokyo/ジャマイカ.png" },
        { "q": "この国はどこ？", "a": "グアテマラ", "img": "images/kokyo/グアテマラ.png" },
        { "q": "この国はどこ？", "a": "ニカラグア", "img": "images/kokyo/ニカラグア.png" },
        { "q": "この国はどこ？", "a": "ホンジュラス", "img": "images/kokyo/ホンジュラス.png" },
        { "q": "この国はどこ？", "a": "エルサルバドル", "img": "images/kokyo/エルサルバドル.png" },
        { "q": "この国はどこ？", "a": "コスタリカ", "img": "images/kokyo/コスタリカ.png" },
        { "q": "この国はどこ？", "a": "パナマ", "img": "images/kokyo/パナマ.png" },
        { "q": "この国はどこ？", "a": "ハイチ", "img": "images/kokyo/ハイチ.png" },
        { "q": "この国はどこ？", "a": "ドミニカ共和国", "img": "images/kokyo/ドミニカ共和国.png" },
        { "q": "この国はどこ？", "a": "ベネズエラ", "img": "images/kokyo/ベネズエラ.png" },
        { "q": "この国はどこ？", "a": "コロンビア", "img": "images/kokyo/コロンビア.png" },
        { "q": "この国はどこ？", "a": "エクアドル", "img": "images/kokyo/エクアドル.png" },
        { "q": "この国はどこ？", "a": "ペルー", "img": "images/kokyo/ペルー.png" },
        { "q": "この国はどこ？", "a": "チリ", "img": "images/kokyo/チリ.png" },
        { "q": "この国はどこ？", "a": "ガイアナ", "img": "images/kokyo/ガイアナ.png" },
        { "q": "この国はどこ？", "a": "スリナム", "img": "images/kokyo/スリナム.png" },
        { "q": "この国はどこ？", "a": "フランス領ギアナ", "img": "images/kokyo/フランス領ギアナ.png" },
        { "q": "この国はどこ？", "a": "ブラジル", "img": "images/kokyo/ブラジル.png" },
        { "q": "この国はどこ？", "a": "ボリビア", "img": "images/kokyo/ボリビア.png" },
        { "q": "この国はどこ？", "a": "パラグアイ", "img": "images/kokyo/パラグアイ.png" },
        { "q": "この国はどこ？", "a": "アルゼンチン", "img": "images/kokyo/アルゼンチン.png" },
        { "q": "この国はどこ？", "a": "ウルグアイ", "img": "images/kokyo/ウルグアイ.png" }
    ];

    window.QUIZ_SUBJECTS = window.QUIZ_SUBJECTS || {};
    window.QUIZ_SUBJECTS[SUBJECT_ID] = {
        id: SUBJECT_ID,
        name: SUBJECT_NAME,
        order: SUBJECT_ORDER,
        questions: questions
    };
})();